package logic

object Config {
    const val ALGORITHM_SENSOR_DISPERSION = 1
    const val ALGORITHM_RANDOM_FIXED_CELLS_VALUE = 10
    const val MUTATE_COUNT_PER_DIVISION = 1
    const val MUTATE_RANGE = 5
    const val OLDEST_GENERATIONS_STORE_COUNT = 10
    const val OLDERST_GENERATION_RELOAD_WORLD_LOCATE_COUNT = 10
    const val CHANCE_TO_MUTATE_IN_PERCENT = 25
    const val ENERGY_FOR_ONE_FOOD = 20
}